[build]
  command = "gatsby build"
  publish = "testtemplate/public"
  base = "testtemplate"

[context.branch-deploy]
  command = "gatsby build"
  publish = "testtemplate/public"
  base = "testtemplate"