[build]
      command = "CI= npm run build"
      publish = "simplemenu/public"
      base = "simplemenu"

    [context.branch-deploy]
      command = "CI= npm run build"
      publish = "simplemenu/public"
      base = "simplemenu"