[build]
    command = "gatsby build"
    publish = "simplemenu/public"
    base = "simplemenu"

  [context.branch-deploy]
    command = "gatsby build"
    publish = "simplemenu/public"
    base = "simplemenu"